package CapstonePackage;

import java.util.ArrayList;

/**
 *
 * @author Donal
 */
public class UICore extends javax.swing.JFrame {

    public static UIManager manager;
    
    /**
     * Creates new form UICore
     */
    public UICore() {
        initComponents();
    }
    
    public UICore(UIManager core){
        manager = core;
        initComponents();
        listView1.setupGUI();
    }
    
    
    
    public void updateComponents(){
        listView1.refresh();
    }
    
    public boolean updateVis(Graph g, String s){
        return visualizer1.setRenderGraph(g, s);
    }
    
    /**
    * Store loaded graph names in the loadedGraphs array. Names can be retrieved from Graph.retrieveAttribute("name")
    * @param loaded 
    */
    public void addGraphs(ArrayList<Graph> loaded){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listView1 = new ListView(manager);
        visualizer1 = new Visualizer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RepGraph");
        setMinimumSize(new java.awt.Dimension(1000, 650));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        listView1.setMaximumSize(new java.awt.Dimension(350, 650));

        javax.swing.GroupLayout listView1Layout = new javax.swing.GroupLayout(listView1);
        listView1.setLayout(listView1Layout);
        listView1Layout.setHorizontalGroup(
            listView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        listView1Layout.setVerticalGroup(
            listView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        getContentPane().add(listView1);
        getContentPane().add(visualizer1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ListView listView1;
    private Visualizer visualizer1;
    // End of variables declaration//GEN-END:variables
}
